version: "3.9"
services:
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama_models:/root/.ollama

  app:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.mono
    environment:
      - OLLAMA_ENDPOINT=http://ollama:11434/api/generate
      - OUTPUT_DIR=/data/output
      - TRANSFORMERS_CACHE=/models
      - HF_HOME=/models
    volumes:
      - ../../output:/data/output
      - ../../models:/models
    depends_on: [ollama]
    command: ["--help"]

volumes:
  ollama_models:
