shots:
  - input: "موضوع: طلب شراء أجهزة\nالنص: نحتاج شراء 10 أجهزة كمبيوتر للقسم الجديد بميزانية 50000 ريال."
    output: |
      **الملخص الإداري:**
      طلب شراء 10 أجهزة كمبيوتر للقسم الجديد

      **الإجراءات المطلوبة:**
      1. القسم المالي - مراجعة الميزانية المتاحة (50,000 ريال)
      2. قسم المشتريات - طرح عروض أسعار
      3. مدير القسم الجديد - تحديد المواصفات المطلوبة

  - input: "موضوع: اجتماع طارئ\nالنص: اجتماع طارئ غداً الساعة 10 صباحاً لمناقشة مشكلة الخادم."
    output: |
      **الملخص الإداري:**
      اجتماع طارئ لحل مشكلة الخادم

      **الإجراءات المطلوبة:**
      1. قسم تقنية المعلومات - حضور الاجتماع غداً 10:00 ص
      2. إدارة النظم - تحضير تقرير المشكلة
      3. المدير التنفيذي - اتخاذ قرار الحل المناسب
